version: '3.8'

services:
  streamlit:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - PORT=${STREAMLIT_SERVER_PORT:-8503}
        - DEFAULT_MODEL=${DEFAULT_MODEL:-llama3.2:latest}
        - OLLAMA_HOST=http://ollama:11434
        - LOG_LEVEL=${LOG_LEVEL:-INFO}
        - STREAMLIT_SERVER_HEADLESS=true
        - STREAMLIT_SERVER_ENABLECORS=${STREAMLIT_SERVER_ENABLECORS:-false}
        - STREAMLIT_SERVER_ENABLEXSRFPROTECTION=${STREAMLIT_SERVER_ENABLEXSRFPROTECTION:-true}
        - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    container_name: idiomapp-streamlit
    ports:
      - "${STREAMLIT_SERVER_PORT:-8503}:${STREAMLIT_SERVER_PORT:-8503}"
    volumes:
      - .:/app
      - ./.env:/app/.env
      - ./docker/docker-entrypoint.sh:/docker-entrypoint.sh:ro
    environment:
      - OLLAMA_HOST=http://ollama:11434  # Override for container communication
      - STREAMLIT_SERVER_HEADLESS=true   # Override for container
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0 # Override to be accessible from host
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false  # Disable usage stats gathering
      - STREAMLIT_UI_HIDE_SIDEBAR_NAV=true  # Simplify UI in container
      - STREAMLIT_THEME_BASE=dark  # Use dark theme
      - STREAMLIT_BROWSER_SERVER_ADDRESS=localhost  # Where to connect from browser
      - STREAMLIT_CLIENT_TOOLBAR_MODE=minimal  # Minimal toolbar
      - STREAMLIT_CLIENT_SHOW_ERROR_DETAILS=true  # Show error details in browser
      - STREAMLIT_WIDE_MODE=true  # Use wide mode by default
    env_file:
      - .env
    depends_on:
      - ollama
    networks:
      - idiomapp-network

  ollama:
    image: ollama/ollama:latest
    container_name: idiomapp-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama-models:/root/.ollama
    networks:
      - idiomapp-network
    # Uncomment this section if you have an NVIDIA GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

networks:
  idiomapp-network:
    driver: bridge 