version: '3.8'

services:
  streamlit:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: idiomapp-streamlit
    ports:
      - "${STREAMLIT_SERVER_PORT:-8503}:${STREAMLIT_SERVER_PORT:-8503}"
    volumes:
      - .:/app
      - ./.env:/app/.env
      - ./docker/docker-entrypoint.sh:/docker-entrypoint.sh:ro
    env_file:
      - .env
    depends_on:
      - ollama
    networks:
      - idiomapp-network

  ollama:
    image: ollama/ollama:latest
    container_name: idiomapp-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama-models:/root/.ollama
    networks:
      - idiomapp-network
    # Uncomment this section if you have an NVIDIA GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

networks:
  idiomapp-network:
    driver: bridge 