[tool.poetry]
name = "idiomapp"
version = "0.1.0"
description = "A web app with graph visualization"
authors = ["User"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.12"
uvicorn = "^0.34.0"
jinja2 = "^3.1.6"
matplotlib = "^3.10.1"
networkx = "^3.4.2"
python-multipart = "^0.0.20"
streamlit = "^1.44.1"
streamlit-agraph = "^0.0.45"
pyvis = "^0.3.2"
watchfiles = "^0.22.0"
ollama = "^0.4.7"
python-dotenv = "^1.1.0"
gtts = "^2.5.4"
langdetect = "^1.0.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api" 