[general]
email = ""
showWarningOnDirectExecution = false
disableWatchdogWarning = true
hideTopBar = false
hideMainMenuButton = false
hideSidebarNav = true
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#4CC9F0"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
runOnSave = true
enableCORS = true
enableXsrfProtection = true
port = 8503

[logger]
level = "INFO" 