[theme]
base = "dark"
primaryColor = "#4361EE"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
runOnSave = true
port = 8503

[logger]
level = "INFO" 